/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.GUI;

import deepspace.DamageToUI;

/**
 *
 * @author manuel
 */
public class DamageView extends javax.swing.JPanel {

    /**
     * Creates new form DamageView
     */
    public DamageView() {
        initComponents();
    }
    
    void setDamage(DamageToUI damage){
        if(damage == null){
            setVisible(false);
        }
        else{
            weaponsLost.setText(damage.getWeaponInfo());
            shieldsLost.setText(Integer.toString(damage.getNShields()));
            repaint();
            revalidate();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shieldsLost_title = new javax.swing.JLabel();
        shieldsLost = new javax.swing.JLabel();
        weaponsLost_title = new javax.swing.JLabel();
        weaponsLost = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        shieldsLost_title.setText("Número de Escudos Perdidos:");

        shieldsLost.setText("jLabel1");

        weaponsLost_title.setText("Armas Perdidas:");

        weaponsLost.setEditable(false);
        weaponsLost.setBackground(new java.awt.Color(239, 239, 239));
        weaponsLost.setColumns(20);
        weaponsLost.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        weaponsLost.setLineWrap(true);
        weaponsLost.setRows(5);
        weaponsLost.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(weaponsLost_title, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shieldsLost, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shieldsLost_title)
                    .addComponent(weaponsLost, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shieldsLost_title, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shieldsLost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weaponsLost_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weaponsLost, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Daño Pendiente");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel shieldsLost;
    private javax.swing.JLabel shieldsLost_title;
    private javax.swing.JTextArea weaponsLost;
    private javax.swing.JLabel weaponsLost_title;
    // End of variables declaration//GEN-END:variables
}
