/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.GUI;

import controller.Controller;
import deepspace.EnemyToUI;
import deepspace.GameState;

/**
 *
 * @author manuel
 */
public class EnemyView extends javax.swing.JPanel {
    
    private DamageView damageView;
    private LootView lootView;
    
    /**
     * Creates new form EnemyView
     */
    public EnemyView() {
        
        initComponents();
        
        damageView = new DamageView();
        damagePanel.add(damageView);
        
        lootView = new LootView();
        lootPanel.add(lootView);
    }
    
    void setEnemy(EnemyToUI enemy){
        
        enemyName.setText(enemy.getName());
        enemyPower.setText(Float.toString(enemy.getAmmoPower()));
        enemyShield.setText(Float.toString(enemy.getShieldPower()));
        
        damageView.setDamage(enemy.getDamage());
        lootView.setLoot(enemy.getLoot());
        
        if(Controller.getInstance().getState() == GameState.BEFORECOMBAT ||
           Controller.getInstance().getState() == GameState.INIT){
            
            lootView.setVisible(false);
            damageView.setVisible(false);
        }
        else{
            
            lootView.setVisible(true);
            damageView.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enemyName_title = new javax.swing.JLabel();
        enemyName = new javax.swing.JLabel();
        enemyPower_title = new javax.swing.JLabel();
        enemyPower = new javax.swing.JLabel();
        enemyShield_title = new javax.swing.JLabel();
        enemyShield = new javax.swing.JLabel();
        loot_title = new javax.swing.JLabel();
        lootPanel = new javax.swing.JPanel();
        damage_title = new javax.swing.JLabel();
        damagePanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(218, 218, 218));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        enemyName_title.setText("Nombre del Enemigo:");

        enemyName.setText("jLabel2");

        enemyPower_title.setText("Potencia de disparo del Enemigo:");

        enemyPower.setText("jLabel1");

        enemyShield_title.setText("Potencia del escudo del Enemigo:");

        enemyShield.setText("jLabel1");

        loot_title.setText("Botín:");

        lootPanel.setBackground(new java.awt.Color(218, 218, 218));

        damage_title.setText("Daño:");

        damagePanel.setBackground(new java.awt.Color(218, 218, 218));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loot_title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(damage_title)
                        .addGap(213, 213, 213))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enemyName_title)
                            .addComponent(enemyPower_title)
                            .addComponent(enemyShield_title))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enemyName)
                            .addComponent(enemyPower)
                            .addComponent(enemyShield))
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(damagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enemyName_title)
                    .addComponent(enemyName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enemyPower)
                    .addComponent(enemyPower_title))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enemyShield)
                    .addComponent(enemyShield_title))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loot_title)
                    .addComponent(damage_title))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(damagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel damagePanel;
    private javax.swing.JLabel damage_title;
    private javax.swing.JLabel enemyName;
    private javax.swing.JLabel enemyName_title;
    private javax.swing.JLabel enemyPower;
    private javax.swing.JLabel enemyPower_title;
    private javax.swing.JLabel enemyShield;
    private javax.swing.JLabel enemyShield_title;
    private javax.swing.JPanel lootPanel;
    private javax.swing.JLabel loot_title;
    // End of variables declaration//GEN-END:variables
}
