/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.GUI;

import deepspace.LootToUI;

/**
 *
 * @author manuel
 */
public class LootView extends javax.swing.JPanel {

    /**
     * Creates new form LootView
     */
    public LootView() {
        initComponents();
    }
    
    void setLoot(LootToUI loot){
        
        hangars.setText(Integer.toString(loot.getnHangars()));
        medals.setText(Integer.toString(loot.getnMedals()));
        shields.setText(Integer.toString(loot.getnShields()));
        supplies.setText(Integer.toString(loot.getnSupplies()));
        weapons.setText(Integer.toString(loot.getnWeapons()));
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        supplies_title = new javax.swing.JLabel();
        supplies = new javax.swing.JLabel();
        weapons_title = new javax.swing.JLabel();
        weapons = new javax.swing.JLabel();
        shields_title = new javax.swing.JLabel();
        shields = new javax.swing.JLabel();
        hangars_title = new javax.swing.JLabel();
        hangars = new javax.swing.JLabel();
        medals_title = new javax.swing.JLabel();
        medals = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        supplies_title.setText("Suministros Obtenidos:");

        supplies.setText("jLabel1");

        weapons_title.setText("Armas Obtenidas:");

        weapons.setText("jLabel1");

        shields_title.setText("Escudos Obtenidos:");

        shields.setText("jLabel1");

        hangars_title.setText("Hangares Obtenidos:");

        hangars.setText("jLabel1");

        medals_title.setText("Medallas Obtenidas:");

        medals.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(weapons_title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(weapons))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(shields_title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(shields))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hangars_title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hangars))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(supplies_title)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(supplies)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(medals_title)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(medals))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplies_title)
                    .addComponent(supplies))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weapons_title)
                    .addComponent(weapons))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shields_title)
                    .addComponent(shields))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hangars_title)
                    .addComponent(hangars))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medals_title)
                    .addComponent(medals))
                .addContainerGap(11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hangars;
    private javax.swing.JLabel hangars_title;
    private javax.swing.JLabel medals;
    private javax.swing.JLabel medals_title;
    private javax.swing.JLabel shields;
    private javax.swing.JLabel shields_title;
    private javax.swing.JLabel supplies;
    private javax.swing.JLabel supplies_title;
    private javax.swing.JLabel weapons;
    private javax.swing.JLabel weapons_title;
    // End of variables declaration//GEN-END:variables
}
