/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.GUI;

import javax.swing.JPanel;
import deepspace.ShieldToUI;
/**
 *
 * @author manuel
 */
public class ShieldView extends JPanel implements CombatElementView{
    
    private boolean selected = false;
    
    /**
     * Creates new form ShieldView
     */
    public ShieldView() {
        initComponents();
        setOpaque(selected);
    }
    
    @Override
    public boolean isSelected () {
        return selected;
    }
    
    void setShield(ShieldToUI shield){
        power.setText(Float.toString(shield.getBoost()));
        uses.setText(Integer.toString(shield.getUses()));
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        power_title = new javax.swing.JLabel();
        power = new javax.swing.JLabel();
        uses_title = new javax.swing.JLabel();
        uses = new javax.swing.JLabel();

        setBackground(new java.awt.Color(30, 255, 78));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(143, 2, 2), 5, true));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        power_title.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        power_title.setText("Potencia:");

        power.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        power.setText("jLabel1");

        uses_title.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        uses_title.setText("Usos:");

        uses.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        uses.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(power_title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(power))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(uses_title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(uses)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(power_title)
                    .addComponent(power))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uses_title)
                    .addComponent(uses)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        selected = !selected;
        setOpaque (selected);
        repaint();
    }//GEN-LAST:event_formMouseClicked
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel power;
    private javax.swing.JLabel power_title;
    private javax.swing.JLabel uses;
    private javax.swing.JLabel uses_title;
    // End of variables declaration//GEN-END:variables
}
