/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.GUI;

import javax.swing.JPanel;
import deepspace.WeaponToUI;
//import deepspace.Weapon;
//import deepspace.WeaponType;
/**
 *
 * @author agd3
 */
public class WeaponView extends JPanel implements CombatElementView {

    private boolean selected = false;
    
    /**
     * Creates new form WeaponView
     */
    public WeaponView() {
        initComponents();
        setOpaque(selected);
    }

    /**
     * @brief Determina si el objeto está seleccionado por el usuario
     * @return selected
     */
    @Override
    public boolean isSelected () {
        return selected;
    }    


    
    /*  Prueba:
    
    public Weapon dameUnArma() {
        return new Weapon("arma", deepspace.WeaponType.LASER, 2);
    }
    */
    
    /**
     * @brief Asocia al panel un objeto ToUI de WeaponView
     * @param weapon : Objeto WeaponToUI que se le pasará a la vista
     */
    void setWeapon(WeaponToUI weapon){
        type.setText(weapon.getType().toString());
        power.setText(Float.toString(weapon.getPower()));
        uses.setText(Integer.toString(weapon.getUses()));
        repaint();
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        type_title = new javax.swing.JLabel();
        power_title = new javax.swing.JLabel();
        uses_title = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        power = new javax.swing.JLabel();
        uses = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 52, 231));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 0, 140), 5));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        type_title.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        type_title.setText("Tipo:");

        power_title.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        power_title.setText("Potencia:");

        uses_title.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        uses_title.setText("Usos:");

        type.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        type.setText("jLabel4");

        power.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        power.setText("jLabel5");

        uses.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        uses.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(power_title)
                    .addComponent(uses_title)
                    .addComponent(type_title, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(power)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(type)
                            .addComponent(uses))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type_title, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(power_title)
                    .addComponent(power))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uses_title)
                    .addComponent(uses))
                .addGap(7, 7, 7))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        selected = !selected;
        setOpaque (selected);
        repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel power;
    private javax.swing.JLabel power_title;
    private javax.swing.JLabel type;
    private javax.swing.JLabel type_title;
    private javax.swing.JLabel uses;
    private javax.swing.JLabel uses_title;
    // End of variables declaration//GEN-END:variables
}
